USE cust_db;

SELECT * 
FROM customer
LIMIT 10;


-- Q1. What is the total REVENUE generated by male vs female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the 
-- average purchase amount?
SELECT customer_id, purchase_amount 
FROM customer
WHERE purchase_amount > (SELECT AVG(purchase_amount) FROM customer)
	AND discount_applied = 'Yes'
LIMIT 20;


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) as 'Average Review Rating'
FROM customer
GROUP BY item_purchased
ORDER BY avg_rev_rat DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2) as 'Average Purchase Amount'
FROM customer
WHERE shipping_type in ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total 
-- revenue between subscribers and non-subscribers.
SELECT subscription_status, 
		COUNT(customer_id) as total_customers,
		ROUND(AVG(purchase_amount),2) as 'Avg Purchasae Amt',
        ROUND(SUM(purchase_amount),2) as 'Total Revenue'
FROM customer
GROUP BY subscription_status;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
	ROUND(SUM(CASE WHEN discount_applied= 'Yes' THEN 1 ELSE 0 END)*100/(COUNT(*)),2) as perc_purc
FROM customer
GROUP BY item_purchased
ORDER BY perc_purc DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning and Loyal based on their total 
-- numbers of previous purchases and show the count of each segment.
with cust_type as (
	SELECT customer_id, 
		CASE 
			WHEN previous_purchases < 2 THEN 'New'
            WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
            ELSE 'Loyal'
		END as customer_type
	FROM customer
)

SELECT customer_type, COUNT(customer_id) as total_customers
FROM cust_type
GROUP BY customer_type;


-- Q8. What are the top 3 most purchased products within each category?
with cte1 as (
	SELECT category, item_purchased, COUNT(customer_id) as total_purchases,
		ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as rk
	FROM customer
	GROUP BY category, item_purchased
	ORDER BY category, COUNT(customer_id) DESC
)
SELECT category, item_purchased, total_purchases
FROM cte1
WHERE rk < 4
ORDER BY category, rk; 




-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also 
-- likely to subscribe?
SELECT subscription_status, COUNT(customer_id) as repeat_customers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group
SELECT age_group, SUM(purchase_amount) as revenue
FROM customer
GROUP BY age_group
ORDER BY revenue DESC;
  